[package]
name = "mc-varint"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
license = "WTFPL"
readme = "README.md"
repository = "https://github.com/luojia65/mc-varint"
documentation = "https://docs.rs/mc-varint"
keywords = ["minecraft"]

[dependencies]
